### ISSUE TITLE
Error in log Error Creating BusinessControllerClass 'DotNetNuke.Modules.Documents.DocumentController, DotNetNuke.Modules.Documents

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Documents#2]
ExceptionHash:ZzlHNgMxMIdZRsFN9hbheNEmjbA=

Message:Error Creating BusinessControllerClass 'DotNetNuke.Modules.Documents.DocumentController, DotNetNuke.Modules.Documents' of module(DNN_Documents) id=(553) in tab(120) and portal(1)

StackTrace:

at DotNetNuke.Services.Search.ModuleIndexer.ThrowLogError(ModuleInfo module, Exception ex)

InnerMessage:Value cannot be null. Parameter name: type

InnerStackTrace:

at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at DotNetNuke.Services.Search.ModuleIndexer.GetModuleList(Int32 portalId)

Source:DotNetNuke

**Comment by valadas** [comment]
Discussion on the other issue: 

-------------

wbonekamp commented
I think the module needs a parameterless constructor...

--------------------

 @mitchelsellers
We are unable to recreate this issue. What version of DNN are you using? What version of .NET? And which version of the DNN Documents Module is in use?

-------------

 @wbonekamp
DNN 9.2 (upgraded from 9.1.1)

Documents 7.0.0

.Net 4.5

Checked the document module for search index, so it's getting indexed

--------------------

 @mitchelsellers
 Owner
mitchelsellers commented 9 days ago
Ok, interesting, we are unable to recreate this with the same environment. Let me continue to review this.

 @wbonekamp
 
 wbonekamp commented 9 days ago • 
 DNN 9.2 upgrade from 911

Documents 7.0.0

.Net 4.5

Checked the document modules for search index

--------------------

 @wbonekamp
 
 Thanks!

Just let me know when you need more info…

We have more than 1 one modules instances on 1 page….

**Comment by mitchelsellers** [comment]
@valadas Are you able to recreate this?

**Comment by valadas** [comment]
No, but I kept it to try with multiple modules on the same page and to test with an upgrade from old version, etc.

**Comment by valadas** [comment]
I just tried various upgrade scenarios and having multiple modules on a page and was not able to reproduce the issue.
Maybe there was a problem during the upgrade...

@wbonekamp in the bin folder of the site there is a file called DotNetNuke.Modules.Documents.dll can you open the file properties and check for anything different than this screenshot:

![image](https://user-images.githubusercontent.com/6371568/42199937-1d9511a6-7e5f-11e8-95be-5acbc1a5d551.png)

**Comment by valadas** [comment]
Close this since there was no reply for some time and we could not reproduce the error.
