### ISSUE TITLE
Cannot edit document, clicking on edit pencil crashes website

### ISSUE THREAD

**Issue by b-creative** [DNNCommunity/DNN.Documents#22]
**Describe the bug:**
When administrating the DNN.Documents module, the admin is no longer able to open up the edit page (in order to edit or delete the document) after having clicked on the pencil in front of the document. The edit page is NOT opening and the whole website takes up all the resources to load.

**To Reproduce:**
1. Install or go to the DNN.Documents module (better do this on a test page)
2. Upload a document
3. Click on the pencil
4. the module tries to opens the file but nothing happens and the site crashes.
5. There are NO errors written in the Admin Log :(

**Expected behavior:**
The expected behavior of clicking on the pencil is to open up the edit page. 

**DNN Information:**
* DNN Version 9.11.1 (occurs in both upgraded versions as in fresh installs)
* Documents Module Version 7.1.0

**Desktop:**
 - OS: Windows 10
 - Occurs in all browsers

**Additional context:**
I tried adding the value 'ItemID' in the 'Keep in Querystring Regular Expression' field, in the SEO section but that didn't do anything.

**Comment by MaiklT** [comment]
Same problem here on different sites since the 9.11.1 upgrade. The application pool stops when trying to edit a document.

**Comment by richcampbell** [comment]
Same here. We get a chrome err_http2_protocol_error message, then the app pool crashes and windows server application logs shows a System.StackOverflowException
