### ISSUE TITLE
DNN 9.13 compatibility 

### ISSUE THREAD

**Issue by maduranga001** [DNNCommunity/DNN.Documents#24]
Hi

Is this compatible with DNN 9.13.6?

Can you please, release the installable version with the latest changes? 

Thank you so much for the great module.

**Comment by james7342** [comment]
I have it running in a DNN 9.13.6 instance without issue.

**Comment by valadas** [comment]
And last release is here https://github.com/DNNCommunity/DNN.Documents/releases/tag/07.01.00

**Comment by maduranga001** [comment]
Thank you very much @valadas 
I checked on 09.13.4 and it works.

Can I know how to handle categories, please?
It says "You can manage lists under "Host" -> "Lists"
But I cannot see it.

**Comment by valadas** [comment]
The documentation probably needs some love, it was written before we had the Persona Bar. I think that is now in vocabularies in modern DNN versions
